# ==================================
# >>> THIS FILE IS AUTOGENERATED <<<
# ==================================

DEFAULT_QUESTIONS = [
    {
        "topic": "Pre-Classic",
        "text": "What do titans start their life as?",
        "answers": ["World-souls", "World Souls"],
    },
    {
        "topic": "Pre-Classic",
        "text": "Orcs had originated from which land?",
        "answers": ["Draenor"],
    },
    {
        "topic": "Pre-Classic",
        "text": "Earthen and other titanic creations were cursed with the \"Curse of Flesh\" by whom?",
        "answers": ["Yogg-Saron", "yogg saron"],
    },
    {
        "topic": "Burning Crusade",
        "text": "By what formal name are the Blood Elves known as?",
        "answers": ["Sin'dorei", "Sin Dorei", "Sindorei"],
    },
    {
        "topic": "Classic",
        "text": "Where was Dalaran located before moving to Northrend?",
        "answers": ["Hillsbrad Foothills", "Hillsbrad"],
    },
    {
        "topic": "Classic",
        "text": "Onyxia spied on Stormwind under the guise of who?",
        "answers": ["Katrana Prestor", "Lady Katrana Prestor", "Lady Prestor"],
    },
    {
        "topic": "Classic",
        "text": "Where did Thrall's Horde shipwreck before reaching Kalimdor?",
        "answers": ["Darkspear Islands", "Darkspear Isles"],
    },
    {
        "topic": "Classic",
        "text": "Who led the Cult of the Damned during the rise of the Scourge?",
        "answers": ["Kel'Thuzad", "Kel Thuzad", "Kelthuzad"],
    },
    {
        "topic": "Burning Crusade",
        "text": "Where was the Exodar originally located before departing? (be specific)",
        "answers": ["Tempest Keep"],
    },
    {
        "topic": "Classic",
        "text": "This dragon aspect was corrupted and started the infinite dragonflight.",
        "answers": ["Nozdormu"],
    },
    {
        "topic": "Cataclysm",
        "text": "In which expansion was Thousand Needles flooded?",
        "answers": ["Cataclysm"],
    },
    {
        "topic": "Burning Crusade",
        "text": "Which swamp was turned into a wasteland over time?",
        "answers": ["Black Morass"],
    },
    {
        "topic": "Wrath",
        "text": "Who became the Lich King after the downfall of Arthas?",
        "answers": ["Bolvar Fordragon", "Bolvar", "Fordragon"],
    },
    {
        "topic": "Pre-Classic",
        "text": "Who was Medivh's apprentice?",
        "answers": ["Khadgar"],
    },
    {
        "topic": "Classic",
        "text": "Who possessed Medivh before his untimely death?",
        "answers": ["Sargeras"],
    },
    {
        "topic": "Cataclysm",
        "text": "What were Gilnean druids originally referred as?",
        "answers": ["Harvest Witches"],
    },
    {
        "topic": "Legion",
        "text": "Who sent Illidan's soul to the Twisting Nether before his resurrection?",
        "answers": ["Gul'dan", "gul dan", "guldan"],
    },
    {
        "topic": "Legion",
        "text": "What noble race of elves lived in isolation for 10,000 years following the War of the Ancients?",
        "answers": ["The Nightborne", "Nightborne", "Shaldorei", "Shal'dorei", "Shal dorei"],
    },
    {
        "topic": "Legion",
        "text": "The Army of the Light was led by this mystical being when the heroes of Azeroth came to Argus.",
        "answers": ["Xe'ra", "Xera", "The Light Mother", "Light Mother", "The Lightmother", "Lithmother", "Mother of the Light", "Prime Naaru Xe'ra", "Prime Naaru Xera"],
    },
    {
        "topic": "Battle for Azeroth",
        "text": "This substance has the potential for great good and great harm, having both mending properties and destructive ones.",
        "answers": ["Azerite"],
    },
    {
        "topic": "Battle for Azeroth",
        "text": "At what location has azerite been found prior to Sargeras stabbing Silithus?",
        "answers": ["Mount Kajaro", "Kajaro"],
    },
    {
        "topic": "Burning Crusade",
        "text": "At what location is Kael'thas Sunstrider killed?",
        "answers": ["Magisters' Terrace"],
    },
    {
        "topic": "Pre-Classic",
        "text": "The naaru O'ros is the descendent of what legendary naaru?",
        "answers": ["Xe'ra", "Xera", "The Light Mother", "Light Mother", "The Lightmother", "Lithmother", "Mother of the Light", "Prime Naaru Xe'ra", "Prime Naaru Xera"],
    },
    {
        "topic": "Legion",
        "text": "This Eredar is the son of Velen and a High General of the Burning Legion.",
        "answers": ["High General Rakeesh", "Rakeesh"],
    },
    {
        "topic": "Burning Crusade",
        "text": "Chimera beasts in Outland are mutated versions of what beast?",
        "answers": ["Rylaks"],
    },
    {
        "topic": "Burning Crusade",
        "text": "This orc clan is known for their use of skulls as headwear.",
        "answers": ["Laughing Skull Clan", "Laughing Skull", "the Laughing Skulls", "the laughing skull", "laughing skull orcs"],
    },
    {
        "topic": "Draenor",
        "text": "What did Aggramar use to defeat the Evergrowth on Draenor?",
        "answers": ["Grond"],
    },
    {
        "topic": "Cataclysm",
        "text": "This pygmy is the leader of the local sand pygmies in Uldum and rides a hyena named Skarf.",
        "answers": ["Sultan Oogah", "Oogah"],
    },
    {
        "topic": "Pandaria",
        "text": "Who lead the rebellion against Garrosh Hellscream?",
        "answers": ["Voljin", "Vol'jin"],
    },
    {
        "topic": "Pandaria",
        "text": "This Horde rebellion included all racial leaders except the at-the-time Warchief and prompted for Horde to reorganize with Vol'jin as the new Warchief.",
        "answers": ["Darkspear Rebellion"],
    },
    {
        "topic": "Classic",
        "text": "Tirion Fordring considers these as a threat and wants them destroyed.",
        "answers": ["Plague bat", "plaguebat"],
    },
    {
        "topic": "Burning Crusade",
        "text": "Name one agent of the Violet Eye who is forever trapped in Karazhan during a mission to find Medivh's Journal.",
        "answers": ["Wravien", "Kamsis", "Gradav"],
    },
    {
        "topic": "Classic",
        "text": "Before Burning Crusade, the Shaman class only belonged to which faction?",
        "answers": ["Horde"],
    },
    {
        "topic": "Classic",
        "text": "Before Burning Crusade, the Paladin class only belonged to which faction?",
        "answers": ["Alliance"],
    },
    {
        "topic": "Battle for Azeroth",
        "text": "These two llamas are Meerah's best friends.",
        "answers": ["Dolly and Dot", "Dot and Dolly", "Dot Dolly", "Dolly Dot"],
    },
    {
        "topic": "Wrath",
        "text": "According to the \"Old Wizard's Almanac\", the descriptions \"as adaptable a race as you will ever find\" and \"can be some of the most highly skilled magic-users\" describe what race?",
        "answers": ["Human", "Humans"],
    },
    {
        "topic": "Wrath",
        "text": "According to the \"Old Wizard's Almanac\", what race is described as possesing moderate magical acuity, mostly in priestly endeavours? ",
        "answers": ["Dwarf", "Dwarves"],
    },
    {
        "topic": "Wrath",
        "text": "According to the \"Old Wizard's Almanac\", the author defined what race as \"remarkably adept arcanists\" and \"are some of the most potent casters the world has ever known\"? ",
        "answers": ["Gnomes", "Gnome"],
    },
    {
        "topic": "Wrath",
        "text": "According to the \"Old Wizard's Almanac\", this race tends to avoid arcane energy \"like it was the Scourge\".",
        "answers": ["Night Elf", "Night elves"],
    },
    {
        "topic": "Wrath",
        "text": "According to the \"Old Wizard's Almanac\", what race brought both powerful wizards and masterful wielders of the Light?",
        "answers": ["Draenei"],
    },
    {
        "topic": "Wrath",
        "text": "According to the \"Old Wizard's Almanac\", this race is extremely powerful, possessing a magical acumen that rivals that of any.",
        "answers": ["High Elves", "High Elf"],
    },
    {
        "topic": "Wrath",
        "text": "According to the \"Old Wizard's Almanac\", what race makes a poor arcanist but display decent magical ability, despite their obvious physical strength?",
        "answers": ["Orc", "Orcs"],
    },
    {
        "topic": "Wrath",
        "text": "According to the \"Old Wizard's Almanac\", this race is highly attuned to the magics of the earth and could rival the archdruids of Darnassus.",
        "answers": ["Tauren"],
    },
    {
        "topic": "Wrath",
        "text": "According to the \"Old Wizard's Almanac\", despite the barbaric reputation and history, what race has a surprising affinity for the magic arts?",
        "answers": ["Troll"],
    },
    {
        "topic": "Wrath",
        "text": "According to the \"Old Wizard's Almanac\", what race has as much magical skill as expected from any living human?",
        "answers": ["Forsaken", "Undead"],
    },
    {
        "topic": "Wrath",
        "text": "According to the \"Old Wizard's Almanac\", a history of prolonged exposure to magical energy has left an indelible mark on what race?",
        "answers": ["Blood Elf", "Blood Elves", "Sin'dorei", "Sindorei", "Sin dorei"],
    },
    {
        "topic": "Wrath",
        "text": "According to the \"Old Wizard's Almanac\", much like their cousins in Kalimdor, this cold weather-living race tends to focus on magic stemming from the earth.",
        "answers": ["Taunka"],
    },
    {
        "topic": "Wrath",
        "text": "According to the \"Old Wizard's Almanac\", what race holds incredible female sorcerers and powerful melee-combat males with the power of water?",
        "answers": ["Naga"],
    },
    {
        "topic": "Wrath",
        "text": "According to the \"Old Wizard's Almanac\", what race has only the most powerful leaders holding the capacity for magic, but many plagued have become necromancers?",
        "answers": ["Nerubian"],
    },
    {
        "topic": "Wrath",
        "text": "According to the \"Old Wizard's Almanac\", this race focuses on the path of the warrior or ranger, and a small amount choose a life of sorcery.",
        "answers": ["Ogre"],
    },
    {
        "topic": "Wrath",
        "text": "According to the \"Old Wizard's Almanac\", what dangerous creatures have features similar to those of night elves, but with twisted demonic bodies?",
        "answers": ["Satyr"],
    },
    {
        "topic": "Wrath",
        "text": "According to the \"Old Wizard's Almanac\", these ancient dragons are among the foremost experts on arcane magic.",
        "answers": ["Blue Dragons", "blue dragonflight"],
    },
    {
        "topic": "Wrath",
        "text": "According to the \"Old Wizard's Almanac\", this race practices geomancy.",
        "answers": ["Quilboar"],
    },
    {
        "topic": "Wrath",
        "text": "According to the \"Old Wizard's Almanac\", what strange race tends to focus on elemental shamanism if they can be bothered to pay attention long enough?",
        "answers": ["Gnoll"],
    },
    {
        "topic": "Wrath",
        "text": "According to the \"Old Wizard's Almanac\", this race has females who prefer to use a dark, perverted form of shamanism, while for males it is quite rare to see them use magic instead of combat.",
        "answers": ["Centaur"],
    },
    {
        "topic": "Wrath",
        "text": "According to the \"Old Wizard's Almanac\", this wolverine-like group are primitive at first glance, but the tribal leaders are often very powerful shaman.",
        "answers": ["Wolvar"],
    },
    {
        "topic": "Wrath",
        "text": "According to the \"Old Wizard's Almanac\", this race is a sworn enemy of the wolvar, but have a nearly identical social system where their leaders are powerful shaman.",
        "answers": ["Oracles"],
    },
    {
        "topic": "Wrath",
        "text": "According to the \"Old Wizard's Almanac\", very few of what race ever become shaman but their free-willed tribes are capable of basic shapeshifting?",
        "answers": ["Furbolg"],
    },
    {
        "topic": "Wrath",
        "text": "According to the \"Old Wizard's Almanac\", these walrus-men practice a form of magic that is similar to shamanism.",
        "answers": ["Tuskarr"],
    },
    {
        "topic": "Wrath",
        "text": "According to the \"Old Wizard's Almanac\", these simple creatures are only capable of eartth magic, and very few of them have perfected a nasty fireball - but that seems to be only fitting for what they protect.",
        "answers": ["Kobold"],
    },
    {
        "topic": "Wrath",
        "text": "According to the \"Old Wizard's Almanac\", these gentle feathered giants posses a natural, druidic energy and are considered what kind of race?",
        "answers": ["Wildkin", "Moonkin", "Owlbear", "Owlkin", "Owlbeast", "Ravenbear"],
    },
    {
        "topic": "Wrath",
        "text": "According to the \"Old Wizard's Almanac\", what race consists of bird-women that are capable of powerful elemental storm magic?",
        "answers": ["Harpy", "harpies"],
    },
    {
        "topic": "Wrath",
        "text": "According to the \"Old Wizard's Almanac\", this race of fish-men are capable of casting earth and water spells, although they are deceiving by appearing as unintelligent creatures.",
        "answers": ["Murloc"],
    },
    {
        "topic": "Wrath",
        "text": "According to the \"Old Wizard's Almanac\", this lobster-like race is considered primitive, but has an innate capacity for water magic.",
        "answers": ["Makrura"],
    },
    {
        "topic": "Wrath",
        "text": "According to the \"Old Wizard's Almanac\", what race is considered to be distrustful to magic, preferring to focus mainly on technological ventures, even though they lack the capacity to understand and appreciate the arcane?",
        "answers": ["Goblin", "Goblins"],
    },
    {
        "topic": "Wrath",
        "text": "According to the \"Old Wizard's Almanac\", this race is considered to be primitive creatures lacking the intelligence necessary for magic.",
        "answers": ["Trogg", "Troggs"],
    },
    {
        "topic": "Wrath",
        "text": "According to the \"Old Wizard's Almanac\", this enormous creature has little to no magical affinity and casters are extremely rare - they will not go down without a fight and their thick hides can withstand several of the most powerful frostbolts.",
        "answers": ["Magnataur"],
    },
    {
        "topic": "Wrath",
        "text": "According to the \"Old Wizard's Almanac\", these half-giants naturally know little to no magic, although some have been trained in necromancy by the Lich King.",
        "answers": ["Vrykul"],
    },
    {
        "topic": "?",
        "text": "Who is the chosen high priestess of the goddess Elune?",
        "answers": ["Tyrande Whisperwind", "Tyrande", "Wisperwind"],
    },
    {
        "topic": "?",
        "text": "This haunted keep is not too far from the borders of Gilneas in southern Silverpine Forest.",
        "answers": ["Shadowfang", "Shadowfang Keep", "SFK"],
    },
    {
        "topic": "Wrath",
        "text": "After Arugal was eventually beheaded by agents of the Horde, what organization continues to use Shadowfang Keep as a base of operations for their schemes?",
        "answers": ["Crown Chemical Company", "Crown Chemical Co", "Chrown Chemical"],
    },
    {
        "topic": "Wrath",
        "text": "Who leads the Crown Chemical Company organization?",
        "answers": ["Hummel", "Apothecary Hummel"],
    },
    {
        "topic": "Classic",
        "text": "This is the blessed blade.",
        "answers": ["Thunderfury"],
    },
    {
        "topic": "Wrath",
        "text": "This giant turtle boat traveling to and from Moa'ki Harbor in Dragonblight is called?",
        "answers": ["The Half Shell", "Half Shell"],
    },
    {
        "topic": "Classic",
        "text": "He is often busy when you talk with him for blackssmithing help because he is making horseshoes for Verner Osgood in Lakeshire.",
        "answers": ["Smith Argus"],
    },
    {
        "topic": "Legion",
        "text": "The Army of the Light deployed these across Argus to help navigate and teleport heroes from place to place.",
        "answers": ["Lightforged Beacons"],
    },
    {
        "topic": "Legion",
        "text": "Spirits of the dishonorable spend eternity in this desolate realm.",
        "answers": ["Hel", "Helheim"],
    },
    {
        "topic": "Legion",
        "text": "Who is the Sea-Witch that rules over the realm of the cursed and fallen vrykul who do not ascend to the Halls of Valor?",
        "answers": ["Helya"],
    },
    {
        "topic": "Classic",
        "text": "This highborne night elf managed to flee Eldre'thalas and the Shen'dralar, but an imp named Pusillin stole his book and key to Eldre'thalas.",
        "answers": ["Azj'Tordin", "Azj tordin", "tordin", "Azj", "azjtordin"],
    },
    {
        "topic": "Pre-Classic",
        "text": "Before the Plague of Undeath, this small lake in Tirisfal Glades was a popular site for picnics and swimming for children who were not yet old enough to swim in the bigger lakes.",
        "answers": ["Stillwater", "Stillwater Pond", "Still water", "Still water pond"],
    },
    {
        "topic": "Classic",
        "text": "This imp stole Azj'Tordin's book of incantations.",
        "answers": ["Pusillin"],
    },
    {
        "topic": "Draenor",
        "text": "Which expansion introduces garrisons?",
        "answers": ["Warlords of Draenor", "Draenor", "Warlords", "WoD"],
    },
    {
        "topic": "Draenor",
        "text": "This powerful ogre mage ruled the Gorian Empire.",
        "answers": ["Imperator Mar'gok", "Margok"],
    },
    {
        "topic": "Pre-Classic",
        "text": "Along side the Light, this is the most fundamental force in existence. ",
        "answers": ["Void"],
    },
    {
        "topic": "Legion",
        "text": "The celebratory feast of an engorged bear heart, held by vrykul kings, is called?",
        "answers": ["Bjornharta"],
    },
    {
        "topic": "Cataclysm",
        "text": "Known for its shadowed woods and rocky beaches, this area of Kalimdor took a heavy toll during the Cataclysm with its landscape completely wrecked.",
        "answers": ["Darkshore"],
    },
    {
        "topic": "Legion",
        "text": "When Maiev Shadowsong went missing during the third invasion of the Burning Legion, who became the interim leader of the Wardens?",
        "answers": ["Sira Moonwarden", "Sira"],
    },
    {
        "topic": "Legion",
        "text": "Per Genn Greymane's orders, Alliance adventurers had killed this banshee captain of The Banshee's Wail in Stormheim.",
        "answers": ["Deathweaver Cassandra", "Cassandra"],
    },
    {
        "topic": "Legion/ / Battle for Azeroth",
        "text": "This battleship serves as part of the Windrunner Fleet for the Horde and first appeared during the battle of Cove of Nashal in Stormheim.",
        "answers": ["The Banshee's Wail", "Banshee's Wail"],
    },
    {
        "topic": "Pandaria",
        "text": "The race of lizard-men that were created by the mogu from the fauna of the Vale of Eternal Blossoms are called?",
        "answers": ["Saurok"],
    },
    {
        "topic": "Burning Crusade",
        "text": "These heavily mutated orcs are created through the Bleeding Hallow clan's blood rituals.",
        "answers": ["Dire orc", "Dire orcs"],
    },
    {
        "topic": "Burning Crusade",
        "text": "These orcs escaped the corruption of the Burning Legion.",
        "answers": ["Mag'har", "Mag'har orc"],
    },
    {
        "topic": "Classic",
        "text": "It is once believed that this banshee was once a beautiful woman who was killed by the undead of Duskwood, but still remained as a 'wraith' of her former self and is consumed by depression and anger over her fate.",
        "answers": ["Blind Mary", "Mary"],
    },
    {
        "topic": "Legion",
        "text": "This is an order of eredar magi lead by the sorcerer Thal'kiel several years before Sargeras' arrival on Argus, who were eventually destroyed by the eredar leadership for consorting with demons and attempting to make Thal'kiel the dictator of Argus.",
        "answers": ["Wakeners", "The Wakeners"],
    },
    {
        "topic": "Cataclysm",
        "text": "This former blade-for-hire became the Twilight's Hammer greatest and deadliest assassin whom they called upon to exterminate Thrall.",
        "answers": ["Asira", "Asira Dawnslayer", "Asira Sunbright", "Dawnslayer", "Sunbright"],
    },
    {
        "topic": "Legion",
        "text": "What location is considered to be the Warden maximum security facility to hold all of the greatest threats to the world?",
        "answers": ["Vault of the Warden", "Vault of the Wardens"],
    },
    {
        "topic": "Pandaria",
        "text": "This powerful, magical titan-forced race was afflicted by the Curse of Flesh, becoming hateful along with their pride driven task to protect the land.",
        "answers": ["Mogu"],
    },
    {
        "topic": "Legion",
        "text": "Gul'dan reopened the Tomb of Sargeras and began the invasion of what?",
        "answers": ["The Burning Legion", "Burning Legion"],
    },
    {
        "topic": "Pre-Classic",
        "text": "Which titan is the creator and leader of the Burning Legion?",
        "answers": ["Sargeras"],
    },
    {
        "topic": "Burning Crusade",
        "text": "This individual is considered to be known as \"The Betrayer\" and master of the Illidari.",
        "answers": ["Illidan Stormrage", "Illidan"],
    },
    {
        "topic": "Pre-Classic",
        "text": "The Lich King betrayed Kil'jaeden and merged with which human?",
        "answers": ["Arthas Menethil", "Arthas"],
    },
    {
        "topic": "Pre-Classic",
        "text": "Who is the master and lord of the Scourge?",
        "answers": ["The Lich King", "Lich King"],
    },
    {
        "topic": "Classic",
        "text": "This organization homes both Horde and Alliance, and together they focus on protecting Azeroth from agencies that seek to destroy it, such as the Burning Legion and the Sourge.",
        "answers": ["Argent Dawn", "the Dawn"],
    },
    {
        "topic": "Burning Crusade",
        "text": "This doomlord remained in the Blasted Lands and assisted in the reopening of the Dark Portal during the second invasion of the Burning Legion.",
        "answers": ["Lord Kazzak", "Kazzak", "Supreme Lord Kazzak"],
    },
    {
        "topic": "Battle for Azeroth",
        "text": "What event was a major conflict fought between the Alliance and Horde for possession of Northern Kalimdor and the destruction of the World Tree Teldrassil?",
        "answers": ["War of the Thorns", "Burning of Teldrassil"],
    },
    {
        "topic": "Legion",
        "text": "What powerful drogbar tribe is lead by Dargrul the Underking?",
        "answers": ["Understone", "Understone Tribe", "The Understone Tribe"],
    },
    {
        "topic": "Burning Crusade",
        "text": "This expansion focuses on the points in Azeroth history relating to the Dark Portal.",
        "answers": ["Burning Crusade", "BC", "The Burning Crusade"],
    },
    {
        "topic": "Classic",
        "text": "The Frostwolves and Stormpike Expedition fight for natural resources and territory where?",
        "answers": ["Alterac Valley", "Alterac", "AV"],
    },
    {
        "topic": "Pandaria",
        "text": "This Hozen is responsible for Sheepie's death, a prized sheep owned by sheep farmer Chee Chee in the Valley of the Four Winds.",
        "answers": ["Krungko Fingerlicker", "Fingerlicker", "Krungko"],
    },
    {
        "topic": "Legion",
        "text": "What is the homunculus's name the Burning Legioin created to infiltrate their enemies by organizing a party in Darnassus?",
        "answers": ["Taylenne Sweetsong", "Taylenne"],
    },
    {
        "topic": "Classic",
        "text": "This human is one of the most famous fishermen in all of Azeroth.",
        "answers": ["Nat", "Nat Pagle", "Pagle"],
    },
    {
        "topic": "Classic",
        "text": "What powerful dragon was trusted by Malygos with safekeeping of the blue dragonflight's most precious artifacts?",
        "answers": ["Azuregos"],
    },
    {
        "topic": "Classic",
        "text": "How many primary dragonflights are there?",
        "answers": ["5"],
    },
    {
        "topic": "Wrath",
        "text": "What was the alliance of four dragonflights (red, bronze, green, and black) created to combat against the blue dragonflight's crusade against magic users called?",
        "answers": ["Wyrmrest Accord"],
    },
    {
        "topic": "Wrath",
        "text": "This Ley-Guardian is the supreme leader of the Oculus and the ley-line conduit operation.",
        "answers": ["Eregos"],
    },
    {
        "topic": "Cataclysm",
        "text": "Who leads the Ramkahen army in Uldum?",
        "answers": ["High Commander Kamses", "Kamses"],
    },
    {
        "topic": "Pre-Classic",
        "text": "Who is the primary goddess of the night elven pantheon?",
        "answers": ["Elune"],
    },
    {
        "topic": "Pre-Classic",
        "text": "The Dragon Aspect of the green dragonflight is known as?",
        "answers": ["Ysera"],
    },
    {
        "topic": "Pre-Classic",
        "text": "This black wyrm dragon was chosen by the Keepers to be one of the five Dragon Aspects, representing the black dragonflight.",
        "answers": ["Neltharion", "Deathwing"],
    },
    {
        "topic": "Burning Crusade",
        "text": "Which titanic watcher awaits in the Guest Chambers wing of Karazhan?",
        "answers": ["Maiden of Virtue", "Virtue"],
    },
    {
        "topic": "Burning Crusade",
        "text": "The iconic saying of \"Run away little girl, run away!\" is said by?",
        "answers": ["Big Bad Wolf", "The Big Bad Wolf"],
    },
    {
        "topic": "Pandaria",
        "text": "This hozen villiage is in the northwest of Jade Forest, right next to Lake Kittitata, and lead by Tooki Tooki.",
        "answers": ["Camp Nooka Nooka", "Nooka Nooka", "Camp Nooka"],
    },
    {
        "topic": "Legion",
        "text": "Who is the chieftain of the Highmountain Rivermane tribe?",
        "answers": ["Jale", "Jale Rivermane", "Rivermane"],
    },
    {
        "topic": "Pandaria",
        "text": "Of the August Celestials that dwell on Pandaria, what is the name of the White Tiger Wild God?",
        "answers": ["Xuen"],
    },
    {
        "topic": "Classic",
        "text": "The vast, ancient swamp in the eastern reaches of Central Kalimdor is known as?",
        "answers": ["Dustwallow", "Dustwallow Marsh", "Dustwallow Swamp"],
    },
    {
        "topic": "Cataclysm",
        "text": "This experimented black whelp is also known as Experiment 25463-D.",
        "answers": ["Atramedes"],
    },
    {
        "topic": "Cataclysm",
        "text": "Maloriak failed his experiment and caused who to become blind?",
        "answers": ["Atramedes"],
    },
    {
        "topic": "Cataclysm",
        "text": "Who is the bumbling minion that is only possessed by a dull of his former intelligence, Malory?",
        "answers": ["Maloriak"],
    },
    {
        "topic": "Cataclysm",
        "text": "He is the son of Cairne Bloodhoof.",
        "answers": ["Baine", "Baine Bloodhoof"],
    },
    {
        "topic": "Classic",
        "text": "Capital city of the Horde's Tauren.",
        "answers": ["Thunder Bluff"],
    },
    {
        "topic": "Classic",
        "text": "Where is Thunder Bluff is located?",
        "answers": ["Mulgore"],
    },
]
